far_planner:
  ros__parameters:
    # Dynamic Planner Default Params
    main_run_freq: 2.5
    voxel_dim: 0.15
    robot_dim: 0.5
    vehicle_height: 0.5
    sensor_range: 30.0
    terrain_range: 30.0
    local_planner_range: 2.0
    visualize_ratio: 0.45
    is_viewpoint_extend: true
    is_multi_layer: false
    is_opencv_visual: false
    is_static_env: true
    is_pub_boundary: false
    is_debug_output: false
    is_attempt_autoswitch: false
    world_frame: map

    # Graph Messager
    # Set to 0 to enable loading graphs from prior map files
    # Set to 1+ for robot-specific graphs
    graph_msger/robot_id: 0

    # Map Handler Params
    map_handler/floor_height: 1.5
    map_handler/cell_length: 5.0
    map_handler/map_grid_max_length: 1000.0
    map_handler/map_grad_max_height: 100.0

    # Dynamic Planner Utility Params
    util/angle_noise: 10.0
    util/accept_max_align_angle: 3.0
    util/obs_inflate_size: 1
    util/new_intensity_thred: 2.0
    util/terrain_free_Z: 0.3
    util/dyosb_update_thred: 4
    util/new_point_counter: 50
    util/dynamic_obs_dacay_time: 20.0
    util/new_points_decay_time: 0.25

    # Dynamic Graph Params
    graph/connect_votes_size: 15
    graph/clear_dumper_thred: 8
    graph/node_finalize_thred: 8
    graph/filter_pool_size: 16

    # Corner Detector Params
    c_detector/resize_ratio: 10.0
    c_detector/filter_count_value: 25
    c_detector/is_save_img: false
    c_detector/img_folder_path: /path

    # Graph Planner Params
    g_planner/converge_distance: 0.75
    g_planner/goal_adjust_radius: 1.0
    g_planner/free_counter_thred: 7
    g_planner/reach_goal_vote_size: 3
    g_planner/path_momentum_thred: 15
