/**:
    ros__parameters:
        # frame id settings
        odom_frame_id: "camera_init"
        base_frame_id: "base_link"

        # icp settings
        feature_extract_enable: false
        point_filter_num: 2
        max_iteration: 5
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: true
        map_file_path: "./test.pcd"

        common:
            lid_topic:  "/velodyne_points"
            imu_topic:  "/imu/data"
            time_sync_en: false
            time_offset_lidar_to_imu: 0.0

        preprocess:
            lidar_type: 2                # 2 for Velodyne
            scan_line: 16
            scan_rate: 10                # Hz
            timestamp_unit: 0            # Check if your driver uses s (0) ms (1) or us (2)
            blind: 2.0

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree: 360.0
            det_range: 80.0
            extrinsic_est_en:  false      # Online refinement of extrinsics
            # Transform from LiDAR to IMU
            extrinsic_T: [-0.186, 0.000, 0.086]
            extrinsic_R: [1.0, 0.0, 0.0,
                          0.0, 1.0, 0.0,
                          0.0, 0.0, 1.0]

        pcd_save:
            pcd_save_en: true
            interval: -1

        global_map:
            map_frame_id: "map"
            map_leaf_size: 0.1
            use_pmf: true
            pmf_max_window_size: 5.0
            pmf_slope: 1.0
            pmf_initial_distance: 0.8
            pmf_max_distance: 1.0

        localization:
            global_frame_id: "map"
            ndt_resolution: 1.0
            ndt_step_size: 0.1
            ndt_trans_epsilon: 0.01
            ndt_max_iter: 30
