/**:
    ros__parameters:
        # frame id settings
        odom_frame_id: "odom_lidar"
        base_frame_id: "base_link"
        map_frame_id:  "map"

        # icp settings
        feature_extract_enable: false
        point_filter_num: 2
        max_iteration: 5
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "./test.pcd"

        common:
            lid_topic:  "/velodyne_points"
            imu_topic:  "/imu/data"
            time_sync_en: false
            time_offset_lidar_to_imu: 0.0

        preprocess:
            lidar_type: 2                 # 2 for Velodyne in fast_lio
            scan_line: 16
            scan_rate: 10                 # Hz
            timestamp_unit: 0             # Check if your driver uses s (0) ms (1) or us (2)
            blind: 0.75                   # avoid points on the vehicle
            max_range: 30.0               # discard points beyond this range

        mapping:
            acc_cov: 0.1
            gyr_cov: 0.1
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            fov_degree: 360.0             # NOTE: not being used
            det_range: 75.0
            extrinsic_est_en:  false      # Online refinement of extrinsics
            # Transform from LiDAR to IMU
            extrinsic_T: [-0.186, 0.000, 0.086]
            extrinsic_R: [1.0, 0.0, 0.0,
                          0.0, 1.0, 0.0,
                          0.0, 0.0, 1.0]

        pcd_save:
            pcd_save_en: true
            interval: -1

        global_cloud:
            map_leaf_size: 0.1

        terrain_cloud:
            use_pmf: true
            pmf_max_window_size: 5.0
            pmf_slope: 0.25
            pmf_initial_distance: 0.3
            pmf_max_distance: 1.0
            ceiling_height_threshold: 1.5
            filter_operator_fov: true
            operator_fov_deg: 120.0

        localization:
            ndt_resolution: 1.0
            ndt_step_size: 0.1
            ndt_trans_epsilon: 0.005
            ndt_max_iter: 30
