/**:
  ros__parameters:
    # Frame IDs
    odom_frame_id: "odom_lidar"
    base_frame_id: "base_link"
    map_frame_id:  "map"

    # NDT Parameters
    localization:
      ndt_resolution: 1.0
      ndt_step_size: 0.1
      ndt_trans_epsilon: 0.005
      ndt_max_iter: 30
